# Generated by Django 6.0 on 2026-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_personagem_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='backstory',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
