# Generated by Django 6.0 on 2026-01-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armaduras', '0002_armadura_extra'),
        ('armas', '0004_alter_arma_dano_ex_alter_arma_dono_and_more'),
        ('personagens', '0003_personagem_backstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonagemArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('equipado', models.PositiveIntegerField(default=0)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donos', to='armas.arma')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='personagens.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='PersonagemArmadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
                ('armadura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donos', to='armaduras.armadura')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to='personagens.personagem')),
            ],
        ),
    ]
