# Generated by Django 6.0 on 2026-01-13 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('n_dado', models.IntegerField(default=1)),
                ('dano', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3)),
                ('n_dado_ex', models.IntegerField(default=1)),
                ('dano_ex', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3)),
                ('efeitos_extras', models.CharField(max_length=5000)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
