# Generated by Django 6.0 on 2026-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='n_dado_ex',
            field=models.IntegerField(default=0),
        ),
    ]
