# Generated by Django 6.0 on 2026-01-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0002_alter_arma_n_dado_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('simples', 'Simples'), ('marcial', 'Marcial')], default='Simples', max_length=7),
        ),
    ]
