# Generated by Django 6.0 on 2026-01-13 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0003_arma_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='dano_ex',
            field=models.CharField(blank=True, choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], max_length=3),
        ),
        migrations.AlterField(
            model_name='arma',
            name='dono',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arma',
            name='efeitos_extras',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='arma',
            name='n_dado_ex',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
