# Generated by Django 6.0 on 2026-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0004_alter_arma_dano_ex_alter_arma_dono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
