# Generated by Django 6.0 on 2026-01-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('leve', 'Leve,'), ('média', 'Média'), ('pesada', 'Pesada')], max_length=10)),
                ('classeDeArmadura', models.PositiveIntegerField()),
                ('peso', models.FloatField(blank=True, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
