# Generated by Django 6.0 on 2026-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armaduras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armadura',
            name='extra',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
