# Generated by Django 6.0 on 2026-01-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armaduras', '0002_armadura_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='armadura',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='dono',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='tipo',
            field=models.CharField(choices=[('leve', 'Leve'), ('média', 'Média'), ('pesada', 'Pesada')], max_length=10),
        ),
    ]
