# Generated by Django 6.0 on 2026-01-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pocao', 'Poção'), ('anel', 'Anel'), ('cajado', 'Cajado'), ('varinha', 'Varinha'), ('item maravilhoso', 'Item Maravilhoso')], max_length=20)),
                ('sintonizacao', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=10000)),
                ('dono', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
