# Generated by Django 6.0 on 2026-01-21 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('tipo', models.CharField(choices=[('origem', 'Origem'), ('geral', 'Geral'), ('épico', 'Épico')], max_length=10)),
                ('pre_requisitos', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(max_length=3000)),
                ('dono', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
